version: "3.9"
networks:
  default:
    external: true
    name: development
services:
  app:
    image: node:14
    user: ${CURRENT_USER}
    stdin_open: true
    tty: true
    working_dir: /opt/app
    ports:
      - '9229:9229'
      - '80:3000'
    entrypoint:
      - '/bin/bash'
    environment:
      - NODE_ENV=development
      - LOCAL_BASE_URL=http://dev.simple-webserver.com.br:1234/
    volumes:
      - ${PWD}:/opt/app 
  redis:
    image: redis:7
